### ISSUE TITLE
Examples for using this with the Serverless framework?

### ISSUE THREAD

**Issue by rvaidya** [nodkz/react-relay-network-layer#24]
The example given looks like it's tied to Express.

**Comment by nodkz** [comment]
Serverless framework: https://github.com/serverless/serverless

It tied to Express only for batching queries. It contains simple express middleware that accepts array of queries in one http request `[{query1}, {query2}]`. Graphql-express only accept `{}`. More details can be found [here](https://github.com/graphql/express-graphql/pull/100) why `graphql-express` does not support arrays.

So if your serverless server side will accept `[{}, {}]` this plugin will 100% compatible with your server. Otherwise, it also works, but will not support batched queries (when at page startup relay makes bunch of queries).

**Comment by rvaidya** [comment]
Thanks, with that information I was able to write a handler for batched queries.

**Comment by nodkz** [comment]
Ok. So I should you provide additional information.

### Client side (react-relay-network-layer)
This is a place in code where is constructed batch request https://github.com/nodkz/react-relay-network-layer/blob/master/src/relay/queriesBatch.js#L21-L27

And where is read response (in the same file)  https://github.com/nodkz/react-relay-network-layer/blob/master/src/relay/queriesBatch.js#L31-L39

**Standard single request**
```js
{
  query:
  variables:
}
```

**Batched request**
```js
[{
  id: // <--- added relay request ID
  query:
  variables:
},
{
  id: // <--- another request ID provided by Relay
  query:
  variables:
},
]
```

### Server side (your handler)

**Standard single response** for details can see [spec](https://github.com/facebook/graphql/blob/master/spec/Section%207%20--%20Response.md)
```js
{
  data: {}, // by spec should be undefined if exists `errors`
  errors: {}, // may be undefined if no error
  extensions: {} | undefined,  // some [additional info](https://github.com/graphql/express-graphql#providing-extensions), eg. performance
}
```

**Batched response**
In the express middleware it constructed in such way https://github.com/nodkz/react-relay-network-layer/blob/master/src/express-middleware/graphqlBatchHTTPWrapper.js#L36-L45
You may see `payload` variable name. I choose this name for standard graphql response.
```js
[
 {
    id: // pass back id obtained from batched request item (Relay request id)
    payload: { // standard graphql response
      data: {}, 
      errors: {},
      extensions: {},
    },
 },
]
```

I pass Relay request `Id` for resolving proper response item with Relay. You may on server run all queries in parallel, and the first ready query immediately send to the client, then attach second and so on, at the end close/end connection/response. So batched response may have a different order for returned items.
