### ISSUE TITLE
Support max batch size

### ISSUE THREAD

**Issue by brad-decker** [nodkz/react-relay-network-layer#39]
### Description of problem
Our application has a search bar that allows a user to search for items on our site. On click the search bar, relay grabs all data for the items that is searchable. When they select an item they are routed to a page that shows all items but the item that they clicked is focused (modal).

The problem is that because we are requesting more data on these items on this page, relay issues a node query for the missing data for each item (315 node queries). relay-network-layer correctly batches these together into one request but i get a 'payload too large' error (413). 

Is there a way to specify a batch size so that i can avoid this issue?

**Comment by nodkz** [comment]
HTTP 413 Request Entity Too Large
The server may reject your request in different places:
- Nginx, apache, load-balancer. Solution for nginx http://www.daveperrett.com/articles/2009/11/18/nginx-error-413-request-entity-too-large/
- `express-graphql` middleware. It has 100kb limit for body ([source](https://github.com/graphql/express-graphql/blob/master/src/parseBody.js#L112-L116)). And this problem was discussed [here](https://github.com/graphql/express-graphql/pull/72) and was declined. I think, that this hard coded limit should be changeable. Developers may have different scenarios when a request is too big (bulk loading, raw base64 file).

----

RRNL does not have the batch size option. It should be done somehow here https://github.com/nodkz/react-relay-network-layer/blob/master/src/relay/queriesBatch.js 
PR welcome. Sorry, I have no free time to do it myself 😔

----

So, if so many problems: on server-side, on client with batching (413) and without batching (too many requests). Anyway 315 times clien, network and server generate/transmit/parse quite huge queries - wasted work.

So:
- Try to fetch data for search with all required data for displaying in list+modal. 
- Or rewrite modal without using fragments connected your components tree. Fetch required data for modals manually like here https://github.com/nodkz/relay-northwind-app/blob/master/app/components/orders/ToggleOrder.js#L29-L44. And rerender component when data will be retrieved for one modal. Also may be useful such wrapper  https://gist.github.com/nodkz/03f28aaa1b66195b517ecf06e92487bf#gistcomment-2023207

**Comment by brad-decker** [comment]
@nodkz Thanks for such a detailed response and all the solutions you've suggested. I think i might take a stab at doing the batch size but until then i'll implement the primeCache call you've suggested. Really appreciate it. 👍
